#!/bin/sh
i=0
while [ true ];do
i=0
    while [ "$i" -lt  10 ]; do
        echo "hello world counts hello world counts hello world counts hello world counts hello world counts hello world counts $i" >>	/data1/log_test.log  
        echo "hello world counts hello world counts hello world counts hello world counts hello world counts hello world counts $i" 
 #       echo "hello world counts hello world counts hello world counts hello world counts hello world counts hello world counts $i" >> tmp_dir/log3
  #      echo "hello world counts hello world counts hello world counts hello world counts hello world counts hello world counts $i" >> tmp_dir/log4
  #      echo "hello world counts hello world counts hello world counts hello world counts hello world counts hello world counts $i" >> tmp_dir/log5
 #@       echo "hello world counts hello world counts hello world counts hello world counts hello world counts hello world counts $i" >> tmp_dir/log6
  #      echo "hello world counts hello world counts hello world counts hello world counts hello world counts hello world counts $i" >> tmp_dir/log7
 #       echo "hello world counts hello world counts hello world counts hello world counts hello world counts hello world counts $i" >> tmp_dir/log8
  #      echo "hello world counts hello world counts hello world counts hello world counts hello world counts hello world counts $i" >> tmp_dir/log9
  #      echo "hello world counts hello world counts hello world counts hello world counts hello world counts hello world counts $i" >> tmp_dir/log10
	sleep 1
	i=$(($i+1))

	done
done
